language: ruby
services:
  - mysql
rvm:
 - 2.3.1
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS myapp_test;'
before_script:
  - cp ./spec/dummy/config/database.yml.test ./spec/dummy/config/database.yml
  - bundle exec rails db:migrate RAILS_ENV=test

script: COVERALLS_REPO_TOKEN=bPQteZngJWF84BYuws90hMmXwWYcMpV9S bundle exec rspec

#after_script:
#  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT