language: ruby
services:
  - mysql
rvm:
 - 2.3.1
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS myapp_test;'
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bundle exec rails db:migrate RAILS_ENV=test

script: bundle exec rails test test/models/*

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT